language: php

php:
    - 7.0

env:
    - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
