<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPosts()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p');
        $qb->from('AppBundle:Post', 'p');
        $qb->orderBy('p.createdAt', 'ASC');
        return $qb;
    }

    public function getTotalViews()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('SUM(p.views) as views');
        $qb->from('AppBundle:Post', 'p');
        return $qb->getQuery()->getOneOrNullResult();
    }
}
