# app/config/security.yml
security:
    firewalls:
        public:
            pattern: ^/api/v1/(auth|_healthcheck)
            security: false
        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

    providers:
        api_key_user_provider:
            id: api_key_user_provider
