# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
